apiVersion: v1
kind: Namespace
metadata:
  name: xmas-services-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xmas-services-operator
  namespace: xmas-services-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xmas-services-operator
rules:
- apiGroups: ["deeptalk.deepshore.de"] # indicates the core API group
  resources: ["xmasservices"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xmas-services-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xmas-services-operator
subjects:
  - kind: ServiceAccount
    name: xmas-services-operator
    namespace: xmas-services-operator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xmas-services-operator
  namespace: xmas-services-operator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmas-services-operator
  name: xmas-services-operator
  namespace: xmas-services-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmas-services-operator
  template:
    metadata:
      labels:
        app: xmas-services-operator
    spec:
      containers:
      - name: xmas-services-operator
        image: xmas-services-operator:v0.0.1
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: "/var/run/shell-operator"
          name: xmas-services-operator
      serviceAccountName: xmas-services-operator
      volumes:
      - name: xmas-services-operator
        persistentVolumeClaim:
          claimName: xmas-services-operator
